/* Classroom presentation: student view never contains the private teacher notes. */
function startRunner(key){
 const x=LR.sessions(S).find(x=>x.key===key);if(!x)return;selectedSession=key;
 const minutes=S.profile.minutes,a=Math.max(3,Math.round(minutes*.125)),b=Math.round(minutes*.375),c=minutes-a-b-a;
 runner={key,stage:0,remaining:a*60,running:false,deadline:0,timer:null,student:false,stages:[{title:'생각 열기',minutes:a,prompt:'경험과 이전 배움을 떠올려 보세요.'},{title:'탐구하고 비교하기',minutes:b,prompt:'사례를 살펴보고 공통점과 차이점을 찾아보세요.'},{title:'설명하고 나누기',minutes:c,prompt:'내 생각의 이유를 친구에게 설명해 보세요.'},{title:'배움 정리하기',minutes:a,prompt:'자료를 덮고 오늘의 배움을 내 문장으로 써 보세요.'}]};
 const l=lessonById(x.lid),plan=S.mats[l.id]?.[matSlot(l,'plan',x.part)];
 if(plan){const doc=document.createElement('template');doc.innerHTML=cleanHtml(plan);const stages=[];for(const table of doc.content.querySelectorAll('table')){const first=table.querySelector('tr'),title=first?.querySelector('th')?.textContent?.trim(),cell=first?.querySelector('td'),match=cell?.textContent.match(/(?:^|\s)(\d{1,3})\s*분/);if(title&&match&&/도입|전개|정리|활동|탐구|성찰|나눔/.test(title)){const teacher=table.textContent.replace(/\s+/g,' ').trim(),quoted=teacher.match(/T\s*[:：]\s*["“]([^"”]+)["”]/);stages.push({title:title.slice(0,70),minutes:Number(match[1]),prompt:quoted?.[1]||'활동을 진행하며 자신의 생각을 정리해 보세요.',teacher});}}if(stages.length>=2&&stages.every(s=>s.minutes>0)&&stages.reduce((a,s)=>a+s.minutes,0)===minutes){runner.stages=stages;runner.remaining=stages[0].minutes*60;runner.fromPlan=true;}}
 $('runDialog').showModal();renderRunner();
}
function formatTimer(seconds){return `${Math.floor(seconds/60).toString().padStart(2,'0')}:${(seconds%60).toString().padStart(2,'0')}`;}
function renderRunner(){if(!runner)return;const x=LR.sessions(S).find(x=>x.key===runner.key),l=lessonById(x.lid),stage=runner.stages[runner.stage],plan=S.mats[l.id]?.[matSlot(l,'plan',x.part)],record=S.records[x.key];
 $('runDialog').classList.toggle('student',runner.student);
 $('runnerContent').innerHTML=`<div class="runner-top"><span class="pill">${x.number}차시 · ${escapeHTML(l.t)}</span><div class="button-row"><button data-action="studentView">${runner.student?'교사용으로 돌아가기':'학생 화면'}</button><button data-action="closeRunner" aria-label="수업 진행 화면 닫기">닫기 ×</button></div></div><div class="runner-question">${escapeHTML(l.question||S.fw.q?.concept||'오늘 어떤 배움을 발견했나요?')}</div><div class="runner-stage">${runner.stage+1} / ${runner.stages.length} · ${stage.title}</div><div class="runner-time" id="runnerTimer" role="timer" aria-label="활동 남은 시간">${formatTimer(runner.remaining)}</div><p style="text-align:center">${stage.prompt}</p><div class="button-row" style="justify-content:center"><button data-action="previousStage" ${runner.stage===0?'disabled':''}>← 이전 활동</button><button class="primary" data-action="timer">${runner.running?'일시정지':'타이머 시작'}</button><button data-action="nextStage" ${runner.stage===runner.stages.length-1?'disabled':''}>다음 활동 →</button></div>
 ${runner.student?'':`<div class="runner-teacher teacher-only"><div class="section-heading"><h3>교사용 수업 메모</h3><span class="pill">학생 화면에서 숨김</span></div><p class="muted small">${runner.fromPlan?"생성한 과정안의 활동과 시간을 불러왔습니다.":`타이머는 ${S.profile.minutes}분 기본 흐름입니다. 실제 과정안에 맞게 시간을 조절하세요.`}</p><div class="button-row"><button data-action="lessTime">−1분</button><button data-action="moreTime">＋1분</button></div><p><b>준비물</b> ${escapeHTML(l.materials||'등록된 준비물이 없습니다.')}</p><p><b>현재 활동의 발문</b> ${escapeHTML(stage.prompt)}</p>${stage.teacher?`<p>${escapeHTML(stage.teacher)}</p>`:""}${S.nodes.filter(n=>n.src===l.id).map(n=>`<p><b>살펴볼 오개념</b> ${escapeHTML(n.m||'—')}</p>`).join('')}${plan?`<details><summary>생성한 과정안 펼치기</summary><div class="doc-body">${cleanHtml(plan)}</div></details>`:'<p class="muted small">자료 보관함에서 과정안을 생성하면 이곳에서 함께 볼 수 있습니다.</p>'}<label>수업 중 관찰 메모<textarea class="short" id="runnerNote" placeholder="학생 반응을 짧게 남기세요.">${escapeHTML(record?.note||'')}</textarea></label><div class="button-row"><button class="primary" data-action="finishRunner">수업 완료하고 기록하기</button></div></div>`}`;
}
function tickRunner(){if(!runner?.running)return;runner.remaining=Math.max(0,Math.ceil((runner.deadline-Date.now())/1000));const el=$('runnerTimer');if(el)el.textContent=formatTimer(runner.remaining);if(runner.remaining===0){clearInterval(runner.timer);runner.running=false;renderRunner();toast('활동 시간이 끝났습니다. 다음 활동으로 이동할 수 있습니다.');}}
function toggleTimer(){if(!runner)return;if(runner.running){tickRunner();clearInterval(runner.timer);runner.running=false;}else{if(runner.remaining<=0)runner.remaining=runner.stages[runner.stage].minutes*60;runner.deadline=Date.now()+runner.remaining*1000;runner.running=true;runner.timer=setInterval(tickRunner,250);}renderRunner();}
function nextStage(delta){if(!runner)return;clearInterval(runner.timer);runner.stage=Math.max(0,Math.min(runner.stages.length-1,runner.stage+delta));runner.running=false;runner.remaining=runner.stages[runner.stage].minutes*60;renderRunner();}
function closeRunner(){if(runner)clearInterval(runner.timer);runner=null;if($('runDialog').open)$('runDialog').close();}
function changeTime(delta){if(!runner)return;runner.remaining=Math.max(0,runner.remaining+delta*60);if(runner.running)runner.deadline=Date.now()+runner.remaining*1000;renderRunner();}
