const {test}=require('node:test');const assert=require('node:assert/strict');const LR=require('../core.js');
function fixture(){const s=LR.empty();s.id='testunit';s.settings.startDate='2026-10-01';s.settings.weekdays=[1,2,3,4,5];s.settings.holidays=['2026-10-09'];s.lessons=[{id:'L01',t:'첫 수업',p:2,s:'탐구1',dates:[],date:''},{id:'L02',t:'둘째 수업',p:2,s:'탐구1',dates:[],date:''},{id:'L03',t:'마지막 수업',p:2,s:'탐구2',dates:[],date:''}];s.nodes=[{id:'N1',src:'L01',c:'사례를 비교한다.',k:'절차',m:'보기만 한다.'}];s.deps=[['L03','N1']];LR.assign(s);return LR.normalize(s);}
test('all individual sessions are dated and holidays skipped',()=>{const s=fixture();assert.deepEqual(LR.sessions(s).map(x=>x.date),['2026-10-01','2026-10-02','2026-10-05','2026-10-06','2026-10-07','2026-10-08']);s.lessons.push({id:'L04',p:1,dates:[],date:''});LR.fillDates(s);assert.equal(s.lessons.at(-1).date,'2026-10-12');});
test('empty weekdays is an error rather than a 400-day loop',()=>{const s=fixture();s.settings.weekdays=[];assert.throws(()=>LR.assign(s),/요일/);});
test('sparse dates do not collapse two practices into one day',()=>{const s=fixture();s.lessons=[{id:'L01',t:'첫',p:1,date:'2026-10-01',dates:['2026-10-01'],s:'a'},{id:'L02',t:'나중',p:1,date:'2026-10-15',dates:['2026-10-15'],s:'a'}];s.deps=[];const sc=LR.schedule(s);assert.equal(sc.events.length,1);assert.equal(sc.events[0].rep,2);assert.ok(sc.warnings.some(x=>x.includes('3회차')));assert.equal(sc.carry[0].n,2);});
test('practice starts after the last session of a multi-period block',()=>{const s=fixture();s.settings.minGap=5;const sc=LR.schedule(s);assert.equal(sc.events.find(e=>e.type==='practice').date,'2026-10-07');});
test('retrieval and practice on same day count once',()=>{const s=fixture();const sc=LR.schedule(s);assert.equal(sc.events.filter(e=>e.date==='2026-10-07').length,1);assert.equal(sc.carry[0].n,2);});
test('move one session preserves all other dates',()=>{const s=fixture();LR.move(s,'L02_1','2026-10-20',false);assert.equal(s.lessons[1].dates[0],'2026-10-20');assert.equal(s.lessons[1].dates[1],'2026-10-06');assert.equal(s.lessons[2].date,'2026-10-07');assert.ok(LR.schedule(s).warnings.length);});
test('move following respects weekends and school holidays',()=>{const s=fixture();LR.move(s,'L02_1','2026-10-08',true);assert.deepEqual(LR.sessions(s).slice(2).map(x=>x.date),['2026-10-08','2026-10-12','2026-10-13','2026-10-14']);});
test('bad dates cannot corrupt a move',()=>{const s=fixture();assert.throws(()=>LR.move(s,'L01_1','2026-02-30',true));assert.equal(s.lessons[0].date,'2026-10-01');});
test('round trip keeps source, settings, standards, materials and records',()=>{const s=fixture();s.source='원문';s.profile.standards='[성취기준] 원문';s.records.L01_1={status:'done',note:'생각',followup:'다음 질문'};s.mats.L01={sheet:'<p>활동</p>'};const x=LR.normalize(JSON.parse(JSON.stringify(s)));assert.equal(x.source,'원문');assert.equal(x.profile.standards,s.profile.standards);assert.deepEqual(x.settings,s.settings);assert.equal(x.records.L01_1.note,'생각');assert.equal(x.mats.L01.sheet,'<p>활동</p>');});
test('legacy v1 backups acquire dates and preserve existing materials',()=>{const x=LR.normalize({unit:'이전 단원',lessons:[{id:'L01',t:'활동',p:2,date:'2026-10-01'}],nodes:[],mats:{L01:{sheet_2:'<p>자료</p>'}}});assert.equal(x.version,2);assert.deepEqual(x.lessons[0].dates,['2026-10-01','2026-10-02']);assert.equal(x.mats.L01.sheet_2,'<p>자료</p>');assert.deepEqual(x.ppt,{});});
test('malformed imports and invalid links are rejected',()=>{assert.throws(()=>LR.normalize({lessons:'x',nodes:[]}));assert.throws(()=>LR.normalize({lessons:[{id:"L1' onclick='x"}],nodes:[]}));const s=fixture();s.nodes[0].src='missing';assert.throws(()=>LR.normalize(s));});
test('unknown future schema does not silently lose data',()=>assert.throws(()=>LR.normalize({...fixture(),version:99}),/최신/));
test('calendar includes real alerts in KST with stable per-unit identity',()=>{const s=fixture(),sc=LR.schedule(s),ics=LR.ics(s,sc,new Date('2026-10-08T00:00:00Z'));assert.match(ics,/BEGIN:VALARM\r\nACTION:DISPLAY\r\nTRIGGER:PT0S/);assert.match(ics,/DTSTART:20261006T100000Z/);assert.match(ics,/DTSTAMP:20261008T000000Z/);assert.match(ics,/UID:testunit-2026-10-06/);});
test('calendar folds UTF-8 lines and escapes reserved characters',()=>{const s=fixture();s.unit='한글'.repeat(70);s.nodes[0].c='질문, 이유; 다음\\단계\n새줄';const ics=LR.ics(s,LR.schedule(s));assert.ok(ics.split('\r\n').every(line=>Buffer.byteLength(line)<=75));assert.match(ics.replace(/\r\n /g,''),/질문\\, 이유\\; 다음\\\\단계\\n새줄/);});
test('zero hour and configured intervals survive round trip',()=>{const s=fixture();s.settings.alarmHour=0;assert.equal(LR.normalize(s).settings.alarmHour,0);});
